language: ruby
bundler_args: --without development --path=~/.bundle
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler bundle_cache
- bundle_cache_install
env:
  global:
  - RAILS_ENV=test
